<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.0.11 INSTALLER - Wednesday 1st of August 2012 06:44:03 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | https://github.com/hybridauth/hybridauth
*  (c) 2009-2011 HybridAuth authors | hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://d3bit.com/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"Yahoo" => array ( 
				"enabled" => true 
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "791832508927.apps.googleusercontent.com", "secret" => "PFtEUi7o2LozWm_hMN__E2_O" ),
				"scope"   => ""
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "182128188586885", "secret" => "37fe9b1e8717629947982d28c87d7668" ),

				// A comma-separated list of permissions you want to request from the user. See the Facebook docs for a full list of available permissions: http://developers.facebook.com/docs/reference/api/permissions.
				"scope"   => "email, user_about_me, offline_access", 

				// The display context to show the authentication page. Options are: page, popup, iframe, touch and wap. Read the Facebook docs for more details: http://developers.facebook.com/docs/reference/dialogs#display. Default: page
				"display" => "" 
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "WMBon2PR4zs1mMJ6R8cgg", "secret" => "Ao6rwZwjlKqKDpJkZcFgVJzraKBfn3CbO8Mpvo3W0k" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "00000000480CDC46", "secret" => "2u0CAb6o3dT8GXjYsBW26xdzXnk8sOlK" ) 
			),

			"MySpace" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "jmbczk9f39fl", "secret" => "CtRwAbUZUc0HYjTF" ) 
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "CKPERVCUB4QLRRNNYZROKCX1GESFKPPOXSQXQYSE1SO3LBGL", "secret" => "IABUURXWQ5TFTPSGOWLFHHSABTDOL4A0IM0HZQGECZZMV5R0" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => "",
	);
